"""Entry point.

    python main.py

Loads your candidate profile (the three base CVs), calibration notes
(regenerated by the learning loop -- see learning_run.py), and applicant
notes (work authorization, salary expectation, etc -- see
config/applicant_notes.example.md), then runs one full pipeline pass:
discover -> extract -> score -> tailor -> sync to Notion -> apply to
anything you've set to "Approved". Safe to run on a schedule (cron /
GitHub Actions) -- dedup means a re-run only picks up what's new, and each
stage only advances jobs that are ready for it. Real submission stays off
by default -- see the safety notes at the top of pipeline/apply.py before
setting AUTO_SUBMIT_CONFIRMED=true.
"""
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

from pipeline import apply as apply_module, orchestrator, scoring  # noqa: E402  (import after load_dotenv)

CONFIG_DIR = Path(__file__).resolve().parent / "config"

if __name__ == "__main__":
    profile = scoring.load_candidate_profile(CONFIG_DIR / "cvs")
    notes = scoring.load_calibration_notes(CONFIG_DIR / "calibration_notes.md")
    applicant_notes = apply_module.load_applicant_notes(CONFIG_DIR / "applicant_notes.md")
    orchestrator.run_all(profile, notes, applicant_notes)
